### PR TITLE
Improve DuraCloud Accessibility

### PR DESCRIPTION
**Pull request by dbernstein**
**Improves accessiibility of DuraCloud**
* * *

**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1264

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)

# What does this Pull Request do?
Tweaks the UI to reduce accessibility related deficiencies including contrast errors, unlabelled form elements and other similar issues that reduce the accessibility of the page.

# How should this be tested?
Run duradmin with the WAVE tool.  See all the errors that were fixed.

main-before

main-after

# Interested parties
Tag (@ mention) interested parties or, if unsure, @duracloud/committers

### CODE REVIEW

**Review by nwoodward — APPROVED** [review]
👍 Looks good.

**Comment by bbranan** [comment]
Overall these changes look great. A few minor issues I noted while reviewing:

The loading spinner (text and icon) shown when spaces are loading sits on top of "Check all" and "Filter" labels. Consider moving this up to the line above (between "Spaces" and "Add Space" button)
loading-spinner-overlap

There's a 1px top border on the spaces list slider that looks odd. It's set on css: `#spaces-list-view-resizer`.
top-of-slider-bar

When the number of items in a space is large, the "show more>" link overlaps with the "Prefix" box label. This becomes especially prominent if the Content Items panel is made smaller
prefix-label-overlap

In the footer, "Duracloud" should be "DuraCloud". Also, do we need the word "Release"? It seems unnecessary (and with the larger font, makes the footer that much longer)

**Review by bbranan — CHANGES_REQUESTED** [review]
It would be ideal to address the above comments before merging.

**Comment by bbranan** [comment]
The issues I mentioned before were all fixed 👍 

A couple other things I noticed while reviewing the latest round of fixes:

1. This doesn't show up in the Wave tool, but the "Login" text (on the login screen) is very low contrast. I'd suggest that we just remove it.
image

2. The "Check all | " label seems to stick around on the Content Items panel even when the checkbox isn't available. I saw this by logging in, selecting a space, then changing to another provider.
image

**Comment by bbranan** [comment]
Following on to the comment about the login page:
* Should any of the text be larger (like the Login button perhaps)?
* Is there a reason why the labels (Username, Password) are so far away from the fields? I also rather like how the current MC has those labels right-aligned.

**Review by bbranan — APPROVED** [review]

**Pull request merged**
