### PR TITLE
Fixed a bunch of duradmin UI bugs for 3.2.4

### PR DESCRIPTION
**Pull request by gadkrumholz**
Fixed image path issue in css in dashboard-manager.jsp.
Added missing jquery-ui images for jquery-ui.css.
Added missing Storage Provider names in jquery.dc.common.js.
Fixed display issue with dashboard-manager.js on mouseover text for file count bar graph.

### CODE REVIEW

**Comment by gadkrumholz** [comment]
Not entirely sure why it passed the Travis test for 3.2.3(commit 5688137) but not after we merged 3.2.4 (commit 1752440) into this branch...

**Comment by dbernstein** [comment]
Yeah - I just release that change list night in order to resolve with some issues were having with the duracloud mill.  I didn't realize I had broken things on the duracloud side.  I'm just testing some code at the moment.  I'm planning to revert the jpa version shortly.

**Comment by dbernstein** [comment]
Hi Gad, 

Sorry for the slow response here.  Your changes look great.  I'm happy to merge them in.  But would you mind resending the pull request against "develop" rather than "master"?  That would help us maintain our process of trying always to update master via develop.

**Comment by gadkrumholz** [comment]
Hi Danny,

Sure thing. I'll close this and create a new PR against develop branch.

Thanks!

**Pull request closed without merging**
