### PR TITLE
DURACLOUD-1102: updates createSpace method to check for existence of space before try…

### PR DESCRIPTION
**Pull request by nwoodward**
…ing to create it

**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1102

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)

# What does this Pull Request do?
A in-depth description of the changes made by this PR. Technical details and possible side effects.

# How should this be tested?

A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR.

Example:
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?

# Interested parties
@duracloud/committers

### CODE REVIEW

**Review by dbernstein — APPROVED** [review]
Looks good.

**Comment by dbernstein** [comment]
Feel free to merge it.

**Comment by nwoodward** [comment]
Noting here that I see the test failure. If this change is accepted then the first HTTP call would be a GET to check if the space exists, and the second call would be the PUT that the test expects. I'm looking to see if the test can expect both calls from the rest helper.

**Comment by dbernstein** [comment]
Good - I had skipped over from the other other PR that had a flapping test - not one that is clearly broken

**Comment by dbernstein** [comment]
Definitely fix that before merging! :)

**Pull request merged**
