### PR TITLE
DURACLOUD-1305: adds check to make sure the space to be added does not already exist

### PR DESCRIPTION
**Pull request by nwoodward**
**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1305

# How should this be tested?
Deploy this PR and observe that the odd behavior described in the Jira issue no longer occurs. 

# Interested parties
@duracloud/committers

### CODE REVIEW

**Comment by dbernstein** [comment]
Looks good:  I'll test it before the release.

**Comment by dbernstein** [comment]
Any idea why the build is breaking here?  Must be a race condition because nothing in the vicinity should have broken those tests.

**Review by dbernstein — APPROVED** [review]
Let's see if we can figure out together what is going on with the flapping tests.

**Comment by nwoodward** [comment]
Sounds good. This failed test is a mystery to me, but I'll keep looking around.

**Comment by dbernstein** [comment]
@nwoodward : I think I have this one sorted.  Stand by.

**Review by dbernstein — APPROVED** [review]

**Pull request merged**
